version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - waste-classifier-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - waste-classifier-network

networks:
  waste-classifier-network:
    driver: bridge
